### ISSUE TITLE
Tall Toasts did not work in my production

### ISSUE THREAD

**Issue by elijahcruz12** [usernotnull/tall-toasts#31]
### Description

When I was pushing my code to my production server (Nginx, Laravel 8.70, PHP 8.0.12, Laravel Octane) I was getting an interesting 404 not found error. This had happened before and after I added octane by the way.

### To Reproduce

I actually fixed this issue by moving the tall-toasts.js to /public/toast/tall-toasts.js

### Expected behavior

The Laravel RouteFacade to actually load it in production. It worked fine in development.

### Additional context

This is a similar issue that gets experienced in [Livewire](https://github.com/livewire/livewire/issues/794). I'd like to open a PR and add an artisan command called toasts:publish that would allow users to move the JavaScript to a /public/toast/tall-toasts.js file. We could then call this in the `post-autoload-dump`, for example, in composer.json if we wish so it could stay updated as we update our projects.

**Comment by usernotnull** [comment]
Hey @elijahcruz12,

Thanks for reporting this.

Feel free to open a PR to include the command option.

As a recap, the user would now have 3 options:
-   include in npm
-   include via @toastScripts
-   **NEW** include via the publish command, which would copy from dist folder to public/**js**/tall-toasts.js. They would then have to include a post autoload dump command in composer to republish on composer updates and would have to include the script tag as usual in his HTML.

For my info, does neither bundling inside npm NOR with the @toastScripts work?

**Comment by elijahcruz12** [comment]
If I leave @toastScripts in, to be able to still load the other inline JavaScript you add, and to allow me to not have to edit much, I can just copy the file over. This way, the @toastScripts still gets the file as /toast/tall-toasts.js, but it gets it from an actual file, rather than the service provider.

**Comment by usernotnull** [comment]
@elijahcruz12 in that case I'll add tall-toasts.js as a publishable asset, just like publishing the view resources. That way it will be automatically added to the public directory, without adding custom commands.

I'll do it soon and let you know to test and feedback...

**Comment by usernotnull** [comment]
@elijahcruz12 before I push a new branch and make changes that could be avoided, can you test the below solution?

In your webpack or bundler config, add this:
```
 .copy('vendor/usernotnull/tall-toasts/dist/js/tall-toasts.js', 'public/js/tall-toasts.js')
```

You can then require that in an HTML script tag pointing to your public `/js/tall-toasts.js` folder.  
Future changes to the js file will be re-bundled by webpack so that's a good alternative too.

Let me know if it solves the issue.

**Comment by elijahcruz12** [comment]
Meanwhile that would work, if you updated the script, and someone runs `composer update` but doesn't run mix, they'll have the outdated version. 

Livewire solved this by including that copies the assets to public, that they recommend if you're having that issue to add it to `post-autoload-dump`. 

That's also why I don't think adding it to mix would be the best method, as you'd also be recompiling your other scripts and styles even if you didn't need to.

**Comment by usernotnull** [comment]
Before you try the above PR, kindly copy the exact error you're getting for me to include it in the troubleshoot section.
It would also be great if you can link the recommendation from livewire for me to reference it in the docs.

Check if the PR resolves the issue. Call `vendor:publish`  and choose `tall-toasts-assets` which will publish to `/public/vendor/tall-toasts`.

If it does I'll update the readme and merge to main. 

Cheers.

**Comment by elijahcruz12** [comment]
The error I was getting was stricly just a 404 not found to /toast/tall-toasts.js 

The problem with this is that this is moving it to a different area. I had started on creating a command last night that moves the javascript files to the litteral /public/toast/tall-toasts.js I finished it, and I was creating a test. I verified it works however using a blank laravel install, as it copied the dist/js folder (including the map), to /public/toast. I think the issue may have become via some nginx configuration that didn't agree, or Google Chrome not agreeing RouteFacades, as I have seen with Livewire doing so.

I didn't edit the readme in the work I had done, but I'll also open a PR so you can check out the command.

**Comment by usernotnull** [comment]
I see what you did. Usually when a package has something publishable the way to go is to declare it the laravel way and publish it as an asset without creating a command to publish, unless the process involves more than copying (such as renaming strings, namespaces, etc...). A good example is telescope or jetstream. The install command does more than just copying.

In our case, since it's just the exact copy of one file, a command would be overkill.
In my PR I reordered the dir structure to highlight the fact that the JS is now publishable, and declared it in the service provider. Whenever there's an update, the composer dump-autoload script can be used to force publish the new assets and should be enough for your use case.

**Comment by elijahcruz12** [comment]
I will test out your PR in a little bit.

**Comment by elijahcruz12** [comment]
Another note on why I did it the way I did it was because I didn't see a a way in `Spatie\LaravelPackageTools\PackageServiceProvider`  to publish in a specific folder, in order to keep the structure of your directive the same.

**Comment by elijahcruz12** [comment]
In your PR, I do not see where you've made it use the file in `/public/vendor/tall-toasts`. Maybe you could make it check using  `File::exists(public_path('/vendor/tall-toasts/js/tall-toasts.js)`, to check if the file exists, and if it does link to that file.

**Comment by usernotnull** [comment]
> Another note on why I did it the way I did it was because I didn't see a way in `Spatie\LaravelPackageTools\PackageServiceProvider` to publish in a specific folder, in order to keep the structure of your directive the same.

This was why I actually made another PR myself, I had a feeling I'll sooner or later have to restructure the paths, so since we're moving in the direction of assets, why not move it from now. I'm going AFK 

> In your PR, I do not see where you've made it use the file in /public/vendor/tall-toasts. Maybe you could make it check using > File::exists(public_path('/vendor/tall-toasts/js/tall-toasts.js), to check if the file exists, and if it does link to that file.

Call `vendor:publish` and choose tall-toasts-assets which will publish to /public/vendor/tall-toasts (it's a simple change in the service provider). The rest of the changes just change how npm builds the js to publish to resources/dist instead of dist.

To include it in your HTML. add a script tag pointing to /vendor/tall-toasts/tall-toasts.js

I did not update the readme to reflect this nor did I add the test, this is a temporary branch to see if it resolves your issue. When it does I'll complete it and push it to main after this weekend.

**Comment by elijahcruz12** [comment]
The problem as well with adding that tag, is the blade directive you have also has a script tag in it, so wouldn't that script tag also still show, potentially causing it to try to load 2 different files?

**Comment by usernotnull** [comment]
You wouldn't need the other script tag, 

```
@toastScripts <<-- remove this
<script src="vendor/tall-toasts/tall-toasts.js" defer></script>
<script src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
```

This works on my side, however, I do have to caution you on something: cache busting when the js changes will be your responsibility.

To be completely honest, this approach will remain on hold until I receive further similar issues. There should be no issue serving `/toast/tall-toasts.js` as the controller should output the file contents properly. If it doesn't, the server settings need to be checked for issues.

**Comment by elijahcruz12** [comment]
Sounds good to me.

**Comment by usernotnull** [comment]
Closing the issue for now to await further reports on this. 

Thanks @elijahcruz12 for sticking to the templates and submitting a PR.

**Comment by coolycow** [comment]
Perhaps the error occurs due to the NGINX settings.
If you turn off the settings for js files, then everything works fine.

An example of settings on my server. It was this block that caused the 404 error.
```
location ~* \.(css|js)$ {
        expires max;
        access_log off;
        log_not_found off;
        add_header 'Cache-Control' 'public';
        add_header 'X-Frame-Options' 'ALLOW-FROM *';
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Credentials' 'true';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    }
```
