### ISSUE TITLE
toast is not showed up when called from livewire mount()

### ISSUE THREAD

**Issue by aldesrahim** [usernotnull/tall-toasts#34]
### Description

Toast wont show when called inside livewire `mount()`, i dont know is this a bug or an expected behavior.

### To Reproduce

1. Add `use WireToast`
2. Place this line of code inside your livewire `mount()` : `toast()->info('Notification from the backend...', 'The Title')->push();`
3. Reload / call your component
4. Toast not show

### Expected behavior

To see a toast

### Screenshots

My livewire component
![image](https://user-images.githubusercontent.com/37100012/141720690-2a9ac5c4-0199-4af6-bb96-d0405d5f3cea.png)

Showing the bug 
![bandicam 2021-11-15 11-06-19-432](https://user-images.githubusercontent.com/37100012/141720897-69711f10-d687-4bab-b49a-482e69836ea1.gif)

Thank you !

**Comment by usernotnull** [comment]
Hey @aldesrahim,

Thanks for reporting this.

I have not used the modal package you are using, but I gave it a quick install to notice the issue.

In regular livewire components, there is no issue when adding toasts inside the `mount` method if the WireToast trait is added.

The way that the `modals` package works is slightly different: you are not loading the livewire tag yourself, they're all automatically added when you add `@livewire('livewire-ui-modal')` at the bottom of the page. I suspect there'll be an issue here.

I even tried a normal dd('AAAA') inside the `mount` method of modals and it didn't work, an empty window opened instead of showing the 'AAAA' string, but that doesn't mean it's an issue with the dd() method itself :)

See if you can, instead of loading the logic inside the `mount` method, load it in a modal-open listener, or call the toast from what opens the modal (JS, another livewire component...).

**Comment by aldesrahim** [comment]
Thank you for your response, really appreciate it.

Oh, its because modal component.. I will try what you suggest.

Thanks for your suggestion 👍 
Keep it up with this great package 🚀 🚀
