### ISSUE TITLE
toasts array is not cleaned

### ISSUE THREAD

**Issue by t7team** [usernotnull/tall-toasts#40]
### Description

toasts array is not cleaned when message is gone

### Screenshots

![Screenshot 2021-11-22 at 15 59 42](https://user-images.githubusercontent.com/11552252/142846332-dc33efff-9584-4a60-8741-d1041cc085ad.png)

**Comment by usernotnull** [comment]
Hey 👋 

This is an expected behaviour. The toasts may not be removed sequentially, so the index has to be kept. There is no issue as the array item is being cleaned when the toast is fully removed. Keep in mind that both front end and backend may push toasts and the array has to remain in sync with minimal ajax requests, so messing with the array index is not optimal.
