### ISSUE TITLE
Paddings are in main div

### ISSUE THREAD

**Issue by t7team** [usernotnull/tall-toasts#41]
### Description

Paddings are in main div 

### Expected behavior

Can you hide paddings in main div and add it when message appears only?
It blocked some buttons on pages.

### Screenshots

![Screenshot 2021-11-22 at 16 11 28](https://user-images.githubusercontent.com/11552252/142847326-ef23acc2-9e07-4342-abfa-90e74dd0837d.png)

**Comment by usernotnull** [comment]
Hey 👋 ,

This should not be an issue as there should be a class called pointer-events-none on the main div.

If you have previously published the vendor views from a previous version, republish them because this issue was previously resolved, or manually add that class.

I suggest you keep an eye on version  changes also because in the latest version, I made some changes to the views to support debug. It's not a breaking change but you'll just miss out on some features if vendor views are not republished or kept in sync.

**Comment by t7team** [comment]
Thanks for the answer.
