### ISSUE TITLE
toast wont appear until there's refresh

### ISSUE THREAD

**Issue by erkinov-wtf** [usernotnull/tall-toasts#456]
i've configured this package and it's working fine. But if i goto other page (im using wire:navigate from livewire's 3rd version), toast wont appear until i hit refresh button. But if i delete wire:navigate it works just fine

**Comment by marchershey** [comment]
Just to be sure, you are adding `use WireToast;` at the top of your class, right? I'm on my way home now, so I'm anxious to give this a test. Lol-- Marc ***@***.***: marc.hershey.coIMPORTANT: This e-mail and any files transmitted with it are confidential and intended solely for the use of the individual or entity to which they are addressed. If you have received this e-mail in error, please notify the system manager. Please note that any views, opinions, or beliefs expressed in this e-mail are solely mine and do not reflect those of the company. Finally, the recipient should check this e-mail and any attachments for the presence of viruses. I do not accept liability for any damage caused by any virus transmitted by this e-mail.On Oct 21, 2023, at 02:32, erkinov ***@***.***> wrote:﻿
i've configured this package and it's working fine. But if i goto other page (im using wire:navigate from livewire's 3rd version), toast wont appear until i hit refresh button. But if i delete wire:navigate it works just fine

**Comment by erkinov-wtf** [comment]
yeah i did add wireToast

**Comment by erkinov-wtf** [comment]
yeah, i found the issue. im using toast inside of my function and the function couldnt find the given 'id', and since i assosiated toast with this 'id' there was nothing. again some tests solved the issue)))

**Comment by marchershey** [comment]
Good deal. Just got home, so that means I can head to bed! :P 

Glad to know you got it sorted out!
