### ISSUE TITLE
Getting the toast only after I refresh the page!

### ISSUE THREAD

**Issue by mokhosh** [usernotnull/tall-toasts#51]
I followed the installation steps.
If I call `toast()->info()->push()` in my `render` method it shows right away, but when I call it in another Livewire method it doesn't show, and this is very weird but if I refresh the page all the toasts from previous session show up!

**Comment by usernotnull** [comment]
Hey @mokhosh ,

To diagnose this further, first, let's make sure you have the `use WireToast` trait in your livewire component.

Next is to swap push() with pushOnNextPage() and see if it makes any difference. The reason is that it depends on the livewire calls occurring in regards to when is the toast being pushed. 

Let me know how it goes.

IF you couldn't figure it out with the above, I appreciate a minimal reproduction code to pinpoint the issue.

**Comment by mokhosh** [comment]
Thanks, I somehow missed the Trait in the docs.

**Comment by usernotnull** [comment]
I have updated the troubleshooting section to reflect this 👍🏼
